# Generated by Django 6.0.4 on 2026-05-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="description_ar",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
