# Generated by Django 6.0.4 on 2026-05-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item_name_en',
        ),
        migrations.RemoveField(
            model_name='orderitemmodification',
            name='ingredient_name_en',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='name_en',
        ),
    ]
