# Generated by Django 6.0.4 on 2026-05-15 12:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_menu_item_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodification',
            name='ingredient_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitemmodification',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
