# Generated by Django 6.0.4 on 2026-06-15

from django.db import migrations


def create_customer_name_trigram_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS customer_name_trgm_idx "
        "ON orders_customer USING gin (name gin_trgm_ops)"
    )


def drop_customer_name_trigram_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute("DROP INDEX IF EXISTS customer_name_trgm_idx")


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_order_branch_order_orders_orde_branch__eed405_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_customer_name_trigram_index,
            drop_customer_name_trigram_index,
        ),
    ]
