# Generated by Codex on 2026-06-30

from django.db import migrations


def create_customer_phone_trigram_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS customer_phone_number_trgm_idx "
        "ON orders_customer USING gin (phone_number gin_trgm_ops)"
    )


def drop_customer_phone_trigram_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute("DROP INDEX IF EXISTS customer_phone_number_trgm_idx")


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0015_remove_customer_contact_uniqueness"),
    ]

    operations = [
        migrations.RunPython(
            create_customer_phone_trigram_index,
            drop_customer_phone_trigram_index,
        ),
    ]
